services:
  - type: web
    name: projekta-backend
    env: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile
    buildCommand: docker build -t projekta-backend ./backend
    startCommand: docker run --rm -p 8000:8000 projekta-backend
    envVars:
      - key: PORT
        value: 8000
    healthCheckPath: /api/health/
    autoDeploy: true